name: CI/CD branch Dev
on:
    push:
        branches: [dev]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Publish to Github Packages Registry
              uses: elgohr/Publish-Docker-Github-Action@v4
              with:
                  name: ispeakvn/trial-test/trial-test
                  registry: docker.pkg.github.com
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
                  dockerfile: dockerfile
                  tags: dev
            - name: SSH and deploy node app
              uses: appleboy/ssh-action@master
              env:
                  E_TAG: dev
                  SOURCE_DIR: ${{ secrets.SOURCE_DEV }}
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
              with:
                  host: ${{ secrets.SSH_HOST_DEV }}
                  username: ${{ secrets.SSH_USERNAME_DEV }}
                  key: ${{ secrets.SSH_KEY_DEV }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE_DEV }}
                  port: ${{ secrets.SSH_PORT_DEV }}
                  envs: SOURCE_DIR, E_TAG, DOCKER_USERNAME, DOCKER_TOKEN
                  script: |
                      cd $SOURCE_DIR
                      docker login docker.pkg.github.com -u $DOCKER_USERNAME -p $DOCKER_TOKEN
                      docker pull docker.pkg.github.com/ispeakvn/trial-test/trial-test:$E_TAG
                      export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
                      docker-compose up -d --force-recreate --no-deps --build enplus_php
